version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Hsn723"
    allow:
      - dependency-type: "all"
    groups:
      docker:
        patterns:
          - "^github.com/containerd/.*"
          - "^github.com/distribution/.*"
          - "^github.com/docker/.*"
          - "^github.com/moby/.*"
          - "^github.com/opencontainers/.*"
      otel:
        patterns:
          - "^github.com/prometheus/.*"
          - "^go.opentelemetry.io/*"
      golang:
        patterns:
          - "^golang.org/x/.*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Hsn723"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Hsn723"
